name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ProcessingTools.Extensions.Dynamic/ProcessingTools.Extensions.Dynamic.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore ProcessingTools.Extensions.Dynamic/ProcessingTools.Extensions.Dynamic.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal ProcessingTools.Extensions.Dynamic/ProcessingTools.Extensions.Dynamic.sln
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: ProcessingTools.Extensions.Dynamic/ProcessingTools.Extensions.Dynamic/ProcessingTools.Extensions.Dynamic.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish AutoMapper
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: ProcessingTools.Extensions.Dynamic/ProcessingTools.Extensions.Dynamic.AutoMapper/ProcessingTools.Extensions.Dynamic.AutoMapper.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
